### ISSUE TITLE
Mark DocsController/GetCustomMeta private to avoid route error

### ISSUE THREAD

**Issue by jafin** [danieleli/Swagger.Net#1]
You might need to mark GetCustomMeta() private as I'm getting a routing error due to it conflicting with the Get() in the same controller.

Multiple actions were found that match the request: 
System.Net.Http.HttpResponseMessage Get() on type Swagger.Net.DocsController
System.Net.Http.HttpResponseMessage GetCustomMeta() on type Swagger.Net.DocsController

**Comment by danieleli** [comment]
Updated, thanks for tip!
