### ISSUE TITLE
The GetMethodSignature was not finding the node in the XML Documentation.

### ISSUE THREAD

**Issue by jafin** [danieleli/Swagger.Net#3]
The GetMethodSignature was not finding the node in the XML Documentation.
This is resulting in the Parameter description was being omitted from the Swagger API

Patch https://gist.github.com/790ed1af3b4836307033

**Comment by danieleli** [comment]
good find.  I'll take a closer look at this tomorrow and merge it in.

thx!

**Comment by mortizbey** [comment]
Has this been pulled?

**Comment by danieleli** [comment]
can you submit it as a pull request?  thx!

**Comment by mortizbey** [comment]
Hi Dan, you can take the patch file and merge it with your version.  It should be the same thing. In the merge documentation just mention the patch and reference the patch url.
